### ISSUE TITLE
Repeated styles

### ISSUE THREAD

**Issue by ghost** [ghallstein/prj-rev-bwfs-dasmoto#3]
There's entirely too much repetition going on in your CSS file. 

https://github.com/ghallstein/prj-rev-bwfs-dasmoto/blob/master/DasmotoArts/resources/css/index.css#L13-L33

These rules are practically identical except for the color of the h2. If you give each item section a shared class like "item", you could refactor all of the shared styles into a single rule like so:

```css
.item h2 {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

Then you can specify the color in its own rule as you already done.

You shouldn't be repeating the font family in every single CSS rule either. Try to write a single rule if you know that all elements will have this style. 

For example:

```css
h1, h2, h3, p, span {
  font-family: Helvetica;
}

/* Or, using the universal selecotor */

* {
  font-family: Helvetica;
}
```
